### ISSUE TITLE
Mismatch between Content-Length declared in headers vs actual content of the body

### ISSUE THREAD

**Issue by danwild** [ivcap-works/ivcap-fastapi#1]
Looking at: 

```python
async def mod_send(message):
    if message["type"] == "http.response.start":
        nonlocal startMsg
        startMsg = message # fix content-length later

    elif message["type"] == "http.response.body":
        body = self.create_reply(message["body"], id)
        message["body"] = body
        startMsg["headers"] = self.set_content_length(len(body), startMsg["headers"])

    print('message:', message) # <---- DEBUG
    await send(message)
```

The 'start' message returns with Content-Length of the original API result, _then_ the 'body' message returns with a different payload for the body content, which has a larger length (due to the nesting added by `create_reply`).

For example, running the `make submit-rpc` demo from [ivcap-python-fastapi-service](https://github.com/ivcap-works/ivcap-python-fastapi-service), we see:

```bash
INFO:     172.17.0.1:62704 - "POST /immediate HTTP/1.1" 200 OK
message: {'type': 'http.response.start', 'status': 200, 'headers': [(b'content-length', b'173'), (b'content-type', b'application/json')]}
message: {'type': 'http.response.body', 'body': b'{"jsonrpc": "2.0", "result": {"$schema": "urn:sd.test:schema.fastapi-test.response.1", "target": "GAAT", "query": "GAT", "alignments": [[[[0, 2], [3, 4]], [[0, 2], [2, 3]]], [[[0, 1], [2, 4]], [[0, 1], [1, 3]]]], "score": 3.0}, "id": 1}'}
```

Start message declares `content-length=173`, which is the length of:

```javascript
{"$schema":"urn:sd.test:schema.fastapi-test.response.1","target":"GAAT","query":"GAT","alignments":[[[[0,2],[3,4]],[[0,2],[2,3]]],[[[0,1],[2,4]],[[0,1],[1,3]]]],"score":3.0}
```

However, the _actual_ body is:

```javascript
{"jsonrpc":"2.0","result":{"$schema":"urn:sd.test:schema.fastapi-test.response.1","target":"GAAT","query":"GAT","alignments":[[[[0,2],[3,4]],[[0,2],[2,3]]],[[[0,1],[2,4]],[[0,1],[1,3]]]],"score":3.0},"id":1}
```

Which has a length of `207`.

I'm not sure why the curl doesn't complain when running the `make submit-rpc` target, but when I run an RPC test query in the mindweaver backend project, I get an error:

```bash
HTTP/1.1 200 OK
date: Mon, 16 Dec 2024 01:51:07 GMT
server: uvicorn
content-length: 84
content-type: application/json

curl: (18) transfer closed with 84 bytes remaining to read
```

And FastAPI:
```
INFO:     172.18.0.1:65058 - "POST /create_agent HTTP/1.1" 200 OK
ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/uvicorn/protocols/http/httptools_impl.py", line 409, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/uvicorn/middleware/proxy_headers.py", line 60, in __call__
    return await self.app(scope, receive, send)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/fastapi/applications.py", line 1054, in __call__
    await super().__call__(scope, receive, send)
  File "/usr/local/lib/python3.11/site-packages/starlette/applications.py", line 113, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/usr/local/lib/python3.11/site-packages/starlette/middleware/errors.py", line 187, in __call__
    raise exc
  File "/usr/local/lib/python3.11/site-packages/starlette/middleware/errors.py", line 165, in __call__
    await self.app(scope, receive, _send)
  File "/usr/local/lib/python3.11/site-packages/starlette/middleware/cors.py", line 85, in __call__
    await self.app(scope, receive, send)
  File "/usr/local/lib/python3.11/site-packages/ivcap_fastapi/json_rpc.py", line 26, in __call__
    await self.call_rpc(scope, receive, send)
  File "/usr/local/lib/python3.11/site-packages/ivcap_fastapi/json_rpc.py", line 69, in call_rpc
    await self.app(scope, mod_receive, mod_send)
  File "/usr/local/lib/python3.11/site-packages/starlette/middleware/exceptions.py", line 62, in __call__
    await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)
  File "/usr/local/lib/python3.11/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app
    raise exc
  File "/usr/local/lib/python3.11/site-packages/starlette/_exception_handler.py", line 42, in wrapped_app
    await app(scope, receive, sender)
  File "/usr/local/lib/python3.11/site-packages/starlette/routing.py", line 715, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/usr/local/lib/python3.11/site-packages/starlette/routing.py", line 735, in app
    await route.handle(scope, receive, send)
  File "/usr/local/lib/python3.11/site-packages/starlette/routing.py", line 288, in handle
    await self.app(scope, receive, send)
  File "/usr/local/lib/python3.11/site-packages/starlette/routing.py", line 76, in app
    await wrap_app_handling_exceptions(app, request)(scope, receive, send)
  File "/usr/local/lib/python3.11/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app
    raise exc
  File "/usr/local/lib/python3.11/site-packages/starlette/_exception_handler.py", line 42, in wrapped_app
    await app(scope, receive, sender)
  File "/usr/local/lib/python3.11/site-packages/starlette/routing.py", line 74, in app
    await response(scope, receive, send)
  File "/usr/local/lib/python3.11/site-packages/starlette/responses.py", line 155, in __call__
    await send({"type": prefix + "http.response.body", "body": self.body})
  File "/usr/local/lib/python3.11/site-packages/starlette/_exception_handler.py", line 39, in sender
    await send(message)
  File "/usr/local/lib/python3.11/site-packages/starlette/_exception_handler.py", line 39, in sender
    await send(message)
  File "/usr/local/lib/python3.11/site-packages/ivcap_fastapi/json_rpc.py", line 67, in mod_send
    await send(message)
  File "/usr/local/lib/python3.11/site-packages/starlette/middleware/errors.py", line 162, in _send
    await send(message)
  File "/usr/local/lib/python3.11/site-packages/uvicorn/protocols/http/httptools_impl.py", line 536, in send
    raise RuntimeError("Response content longer than Content-Length")
RuntimeError: Response content longer than Content-Length
```

**Comment by danwild** [comment]
fyi played with some workarounds: https://github.com/science-digital/mindweaver/blob/main/backend/ivcap/json_rpc.py#L53

**Comment by danwild** [comment]
Hmm, I was incorrect here - the initial smaller content-length is _not_ sent in the response. 

There is something else at (still unknown) play, will close.

We're not using `use_try_later_middleware` in the mindweaver app yet, but when I added it - this issue disappeared... (however this behaviour could not be replicated in the [ivcap-python-fastapi-service](https://github.com/ivcap-works/ivcap-python-fastapi-service) demo 🤷‍♂️)

Confuse.
